url: https://scc-digitalhub.github.io
baseurl: /

# Site settings
title: Digital Hub
email: your-email@domain.com
description: "An open-source platform for digital transformation, open data and open service management"


# Team names, titles and social links
people:
- name: Claudio Ballardini
  pic: img/team/placeholder.png
  position: Software Engineer, DSLab, FBK
  links:

- name: Vitor Bezerra
  pic: img/team/vbezerra.jpg
  position: Software Engineer, DSLab, FBK
  links:
    - icon: envelope-o
      url: mailto:vbezerra@fbk.eu

- name: Alberto Carotti
  pic: img/team/acarotti.jpg
  position: Software Engineer, Dedagroup spa
  links:
    - icon: envelope-o
      url: mailto:alberto.carotti@dedagroup.it

- name: Albana Celepija
  pic: img/team/placeholder.png
  position: Software Developer, DSLab, FBK
  links:

- name: Matteo Chini
  pic: img/team/placeholder.png
  position: Software Developer, DSLab, FBK
  links:

- name: Fabio Fais
  pic: img/team/placeholder.png
  position: DevOps, DSLab, FBK
  links:

- name: Raman Kazhamiakin
  pic: img/team/placeholder.png
  position: CTO, DSLab, FBK
  links:

- name: Nawaz Khurshid
  pic: img/team/khurshid.jpg
  position: Software Engineer, DSLab, FBK
  links:

- name: Andrea Lattaruolo
  pic: img/team/alattaruolo.jpg
  position: Software Engineer, DSLab, FBK
  links:
    - icon: envelope-o
      url: mailto:alattaruolo@fbk.eu

- name: Matteo Martini
  pic: img/team/placeholder.png
  position: Data Scientist, DSLab, FBK
  links:

- name: Michele Nori
  pic: img/team/nori.jpg
  position: Software Architect, DSLab, FBK
  links:
    - icon: envelope-o
      url: mailto:nori@fbk.eu

- name: Matteo Saloni
  pic: img/team/placeholder.png
  position: Software Architect, DSLab, FBK
  links:

- name: Erica Tomaselli
  pic: img/team/ertomaselli.jpg
  position: Software Engineer, Dedagroup spa
  links:

- name: Luca Trubbiani
  pic: img/team/ltrubbiani.jpg
  position: Software Engineer, DSLab, FBK
  links:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/scc-digitalhub

# Postal address (add as many lines as necessary)
address:
  - line: Via Sommarive 18, 38123 TN, Italy

# Build settings
markdown: kramdown
permalink: pretty